### ISSUE TITLE
Question: What is the reason of "@ApplicationContext"?

### ISSUE THREAD

**Issue by Rainer-Lang** [janishar/android-mvp-interactor-architecture#4]
Why is it used - and for what?
Thanks.

UPDATE: Is it something like ```@Named```?
UPDATE 2: I found something: https://stackoverflow.com/a/39966489/4534276
I think my question is now "answered". :-)

**Comment by Rainer-Lang** [comment]
But I just want to know what do you suggest. What are the pros and cons?

**Comment by amitshekhariitbhu** [comment]
Yes, that is `Named` and it is also for readability purpose so that caller knows which context(application or other).
